version: '3.4'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
