version: "3.4"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/home/app/backend
      - ./backend/staticfiles:/home/app/backend/staticfiles
      - ./backend/mediafiles:/home/app/backend/mediafiles
    expose:
      - 8000
    entrypoint: poetry run bash entrypoint.sh
    command: poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000

  nginx:
    container_name: nginx
    build:
      context:  nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

      - ./backend/staticfiles:/home/app/backend/staticfiles
      - ./backend/mediafiles:/home/app/backend/mediafiles
    depends_on:
        backend:
          condition: service_healthy