[tool.poetry]
name = "shop"
version = "0.1.0"
description = ""
authors = ["Iulia Zagornova <zagornowwa.julia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
