# Generated by Django 4.2.5 on 2023-11-22 17:46

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_created_remove_order_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'Подтверждение'), (1, 'Выполнен'), (2, 'Отменен')], default=0, max_length=100, no_check_for_status=True),
        ),
    ]
