# Generated by Django 4.2.5 on 2023-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Онлайн перевод')], default=0, verbose_name='Тип оплаты'),
        ),
    ]
