# Generated by Django 4.2.5 on 2023-11-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
