# Generated by Django 4.2.5 on 2023-11-22 19:23

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_payment_type_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=model_utils.fields.StatusField(choices=[('CONFIRMATION', 'Подтверждение'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CONFIRMATION', max_length=100, no_check_for_status=True),
        ),
    ]
