# Generated by Django 4.2.5 on 2023-11-22 19:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor=model_utils.fields.StatusField(choices=[('CONFIRMATION', 'Подтверждение'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CONFIRMATION', max_length=100, no_check_for_status=True), null=True, verbose_name='Дата отмены заказа', when={'CANCELED'}),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor=model_utils.fields.StatusField(choices=[('CONFIRMATION', 'Подтверждение'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CONFIRMATION', max_length=100, no_check_for_status=True), null=True, verbose_name='Дата выполнения заказа', when={'COMPLETED'}),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ONLINE_TRANSFER', 'Онлайн перевод')], default='ONLINE_TRANSFER', max_length=30, verbose_name='Тип оплаты'),
        ),
    ]
