# Generated by Django 4.2.5 on 2023-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productitem_quantity'),
        ('orders', '0007_order_canceled_date_order_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='Дата отмены заказа', when={'CANCELED'}),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_date',
            field=model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='Дата выполнения заказа', when={'COMPLETED'}),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=model_utils.fields.StatusField(choices=[('CONFIRMATION', 'Подтверждение'), ('COMPLETED', 'Выполнен'), ('CANCELED', 'Отменен')], default='CONFIRMATION', max_length=100, no_check_for_status=True, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.product')),
            ],
        ),
    ]
