# Generated by Django 4.2.5 on 2023-10-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductListItem',
            new_name='ProductItem',
        ),
    ]
